### ISSUE TITLE
onEvent() function ?

### ISSUE THREAD

**Issue by Rush4iot** [lorabasics/basicmac#2]
Hi,

[First page](https://doc.sm.tc/mac/programming.html) of the documentation mentions the `onEvent()` function. It used to be in LMiC 1.6, is it still there in LMiC 1.9 ?
A [search on the code](https://github.com/lorabasics/basicmac/search?q=onevent&unscoped_q=onevent) does not return any result.

Olivier

**Comment by Rush4iot** [comment]
I figured that we have to register a hook in app.svc like `
hook.lwm_event: onEvent` as described [here](https://doc.sm.tc/mac/lwmux.html#lwm-event)
Please be more explicit in the documentation, it seems that onEvent is a leftover from 1.6.

**Comment by mkuyper** [comment]
The event handling function is still needed and must be supplied to the core stack. However, it has been renamed to `onLmicEvent()`; this will be fixed in the documentation.

The *lwmux* service contains an implementation of this function and, as you correctly pointed out, provides hooks for applications and other services/modules to participate in the processing of those events. Use of the *lwmux* module by applications is highly recommended.

Note that there is a [macro](https://github.com/lorabasics/basicmac/search?q=DECL_ON_LMIC_EVENT&unscoped_q=DECL_ON_LMIC_EVENT) that is used to declare the function, making it a bit harder to find using code search.
